### ISSUE TITLE
Account Locked

### ISSUE THREAD

**Issue by neuegram** [neuegram/Ghost#1]
Snapchat is locking accounts using 3rd party services. I have yet to workaround this, but efforts are being made. I will update this issue with progress.

**Comment by sysr-q** [comment]
You mean you don't have an unlimited amount of Snapchat accounts in a JSON file that you registered years ago?
I mean what. No.

**Comment by neuegram** [comment]
@sysr-q Not everyone does :) Project is put on hold for now. Busy with a lot of other things. I told you my plan to resolve this no?

**Comment by hako** [comment]
Issue is now resolved in https://github.com/neuegram/Ghost/pull/3

> You mean you don't have an unlimited amount of Snapchat accounts in a JSON file that you registered years ago?

@sysr-q I would like to point out that it's now possible to register Snapchat accounts using the [srcli (Snapchat Registration CLI)](https://github.com/neuegram/Ghost/tree/master/srcli) that registers and exports to JSON. :)
